spring:  servlet:    multipart:      enabled: true      max-file-size: 20MB      max-request-size: 20MB      
server:
  port: 8080
  servlet:
    session:
      timeout: 30
  ssl:
    enabled: true
    key-alias: tollgate-keys
    key-store: ..\tollgate-keys.pkcs12
    key-store-password: 'chameleon'
    key-password: 'chameleon'
    trust-store: ..\tollgate-trust.pkcs12
    trust-store-password: 'chameleon'