/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chameleon_tollgate_MainActivity */

#ifndef _Included_com_chameleon_tollgate_MainActivity
#define _Included_com_chameleon_tollgate_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chameleon_tollgate_MainActivity
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chameleon_tollgate_MainActivity_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
